/* eslint-disable eol-last */
/* eslint-disable no-misleading-character-class */
/* eslint-disable lines-between-class-members */
/* eslint-disable no-labels */
/* eslint-disable no-throw-literal */
/* eslint-disable n/no-callback-literal */
/* eslint-disable dot-notation */
/* eslint-disable no-mixed-operators */
/* eslint-disable no-cond-assign */
/* eslint-disable no-self-compare */
/* eslint-disable valid-typeof */
/* eslint-disable no-new-func */
/* eslint-disable no-unreachable-loop */
/* eslint-disable no-return-assign */
/* eslint-disable no-proto */
/* eslint-disable no-extend-native */
/* eslint-disable no-unneeded-ternary */
/* eslint-disable camelcase */
/* eslint-disable no-use-before-define */
/* eslint-disable no-lone-blocks */
/* eslint-disable no-unused-vars */
/* eslint-disable no-unexpected-multiline */
/* eslint-disable no-useless-call */
/* eslint-disable array-callback-return */
/* eslint-disable no-sparse-arrays */
/* eslint-disable prefer-regex-literals */
/* eslint-disable new-cap */
/* eslint-disable no-undef */
/* eslint-disable no-redeclare */
/* eslint-disable no-prototype-builtins */
/* eslint-disable yoda */
/* eslint-disable no-void */
/* eslint-disable no-unmodified-loop-condition */
/* eslint-disable space-before-function-paren */
/* eslint-disable space-in-parens */
/* eslint-disable curly */
/* eslint-disable eqeqeq */
/* eslint-disable no-sequences */
/* eslint-disable comma-dangle */
/* eslint-disable no-useless-escape */
/* eslint-disable semi */
/* eslint-disable indent */
/* eslint-disable wrap-iife */
/* eslint-disable no-var */
/* eslint-disable one-var */
/* eslint-disable no-unused-expressions */